//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace CostErrDeal.DBInfoWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TestConnOperationCompleted;
        
        private System.Threading.SendOrPostCallback setTiptopPreAccountListOperationCompleted;
        
        private System.Threading.SendOrPostCallback setTiptopPreAccountListTest2OperationCompleted;
        
        private System.Threading.SendOrPostCallback getPayNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTipTopAccountNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback delTiptopPreAccountNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPayStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback delALLTiptopPreAccountNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTiptopOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTiptopDBInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::CostErrDeal.Properties.Settings.Default.EsignKit_DBInfoWS_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestConnCompletedEventHandler TestConnCompleted;
        
        /// <remarks/>
        public event setTiptopPreAccountListCompletedEventHandler setTiptopPreAccountListCompleted;
        
        /// <remarks/>
        public event setTiptopPreAccountListTest2CompletedEventHandler setTiptopPreAccountListTest2Completed;
        
        /// <remarks/>
        public event getPayNoCompletedEventHandler getPayNoCompleted;
        
        /// <remarks/>
        public event getTipTopAccountNoCompletedEventHandler getTipTopAccountNoCompleted;
        
        /// <remarks/>
        public event delTiptopPreAccountNoCompletedEventHandler delTiptopPreAccountNoCompleted;
        
        /// <remarks/>
        public event getNoCompletedEventHandler getNoCompleted;
        
        /// <remarks/>
        public event getStatusCompletedEventHandler getStatusCompleted;
        
        /// <remarks/>
        public event GetPayStatusCompletedEventHandler GetPayStatusCompleted;
        
        /// <remarks/>
        public event delALLTiptopPreAccountNoCompletedEventHandler delALLTiptopPreAccountNoCompleted;
        
        /// <remarks/>
        public event SendTiptopCompletedEventHandler SendTiptopCompleted;
        
        /// <remarks/>
        public event GetTiptopDBInfoCompletedEventHandler GetTiptopDBInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestConn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TestConn() {
            this.Invoke("TestConn", new object[0]);
        }
        
        /// <remarks/>
        public void TestConnAsync() {
            this.TestConnAsync(null);
        }
        
        /// <remarks/>
        public void TestConnAsync(object userState) {
            if ((this.TestConnOperationCompleted == null)) {
                this.TestConnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestConnOperationCompleted);
            }
            this.InvokeAsync("TestConn", new object[0], this.TestConnOperationCompleted, userState);
        }
        
        private void OnTestConnOperationCompleted(object arg) {
            if ((this.TestConnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestConnCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setTiptopPreAccountList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string setTiptopPreAccountList(string Argu1, System.Data.DataSet Argu2) {
            object[] results = this.Invoke("setTiptopPreAccountList", new object[] {
                        Argu1,
                        Argu2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setTiptopPreAccountListAsync(string Argu1, System.Data.DataSet Argu2) {
            this.setTiptopPreAccountListAsync(Argu1, Argu2, null);
        }
        
        /// <remarks/>
        public void setTiptopPreAccountListAsync(string Argu1, System.Data.DataSet Argu2, object userState) {
            if ((this.setTiptopPreAccountListOperationCompleted == null)) {
                this.setTiptopPreAccountListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetTiptopPreAccountListOperationCompleted);
            }
            this.InvokeAsync("setTiptopPreAccountList", new object[] {
                        Argu1,
                        Argu2}, this.setTiptopPreAccountListOperationCompleted, userState);
        }
        
        private void OnsetTiptopPreAccountListOperationCompleted(object arg) {
            if ((this.setTiptopPreAccountListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setTiptopPreAccountListCompleted(this, new setTiptopPreAccountListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setTiptopPreAccountListTest2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string setTiptopPreAccountListTest2(string Argu1) {
            object[] results = this.Invoke("setTiptopPreAccountListTest2", new object[] {
                        Argu1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setTiptopPreAccountListTest2Async(string Argu1) {
            this.setTiptopPreAccountListTest2Async(Argu1, null);
        }
        
        /// <remarks/>
        public void setTiptopPreAccountListTest2Async(string Argu1, object userState) {
            if ((this.setTiptopPreAccountListTest2OperationCompleted == null)) {
                this.setTiptopPreAccountListTest2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetTiptopPreAccountListTest2OperationCompleted);
            }
            this.InvokeAsync("setTiptopPreAccountListTest2", new object[] {
                        Argu1}, this.setTiptopPreAccountListTest2OperationCompleted, userState);
        }
        
        private void OnsetTiptopPreAccountListTest2OperationCompleted(object arg) {
            if ((this.setTiptopPreAccountListTest2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setTiptopPreAccountListTest2Completed(this, new setTiptopPreAccountListTest2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPayNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPayNo(string Argu1, string Argu2) {
            object[] results = this.Invoke("getPayNo", new object[] {
                        Argu1,
                        Argu2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPayNoAsync(string Argu1, string Argu2) {
            this.getPayNoAsync(Argu1, Argu2, null);
        }
        
        /// <remarks/>
        public void getPayNoAsync(string Argu1, string Argu2, object userState) {
            if ((this.getPayNoOperationCompleted == null)) {
                this.getPayNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPayNoOperationCompleted);
            }
            this.InvokeAsync("getPayNo", new object[] {
                        Argu1,
                        Argu2}, this.getPayNoOperationCompleted, userState);
        }
        
        private void OngetPayNoOperationCompleted(object arg) {
            if ((this.getPayNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPayNoCompleted(this, new getPayNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTipTopAccountNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getTipTopAccountNo(string Argu1, string Argu2) {
            object[] results = this.Invoke("getTipTopAccountNo", new object[] {
                        Argu1,
                        Argu2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTipTopAccountNoAsync(string Argu1, string Argu2) {
            this.getTipTopAccountNoAsync(Argu1, Argu2, null);
        }
        
        /// <remarks/>
        public void getTipTopAccountNoAsync(string Argu1, string Argu2, object userState) {
            if ((this.getTipTopAccountNoOperationCompleted == null)) {
                this.getTipTopAccountNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTipTopAccountNoOperationCompleted);
            }
            this.InvokeAsync("getTipTopAccountNo", new object[] {
                        Argu1,
                        Argu2}, this.getTipTopAccountNoOperationCompleted, userState);
        }
        
        private void OngetTipTopAccountNoOperationCompleted(object arg) {
            if ((this.getTipTopAccountNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTipTopAccountNoCompleted(this, new getTipTopAccountNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/delTiptopPreAccountNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string delTiptopPreAccountNo(string Argu1, string Argu2) {
            object[] results = this.Invoke("delTiptopPreAccountNo", new object[] {
                        Argu1,
                        Argu2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void delTiptopPreAccountNoAsync(string Argu1, string Argu2) {
            this.delTiptopPreAccountNoAsync(Argu1, Argu2, null);
        }
        
        /// <remarks/>
        public void delTiptopPreAccountNoAsync(string Argu1, string Argu2, object userState) {
            if ((this.delTiptopPreAccountNoOperationCompleted == null)) {
                this.delTiptopPreAccountNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OndelTiptopPreAccountNoOperationCompleted);
            }
            this.InvokeAsync("delTiptopPreAccountNo", new object[] {
                        Argu1,
                        Argu2}, this.delTiptopPreAccountNoOperationCompleted, userState);
        }
        
        private void OndelTiptopPreAccountNoOperationCompleted(object arg) {
            if ((this.delTiptopPreAccountNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delTiptopPreAccountNoCompleted(this, new delTiptopPreAccountNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getNo(string Argu1, string Argu2) {
            object[] results = this.Invoke("getNo", new object[] {
                        Argu1,
                        Argu2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getNoAsync(string Argu1, string Argu2) {
            this.getNoAsync(Argu1, Argu2, null);
        }
        
        /// <remarks/>
        public void getNoAsync(string Argu1, string Argu2, object userState) {
            if ((this.getNoOperationCompleted == null)) {
                this.getNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNoOperationCompleted);
            }
            this.InvokeAsync("getNo", new object[] {
                        Argu1,
                        Argu2}, this.getNoOperationCompleted, userState);
        }
        
        private void OngetNoOperationCompleted(object arg) {
            if ((this.getNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNoCompleted(this, new getNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getStatus(string Argu1, string Argu2) {
            object[] results = this.Invoke("getStatus", new object[] {
                        Argu1,
                        Argu2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getStatusAsync(string Argu1, string Argu2) {
            this.getStatusAsync(Argu1, Argu2, null);
        }
        
        /// <remarks/>
        public void getStatusAsync(string Argu1, string Argu2, object userState) {
            if ((this.getStatusOperationCompleted == null)) {
                this.getStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStatusOperationCompleted);
            }
            this.InvokeAsync("getStatus", new object[] {
                        Argu1,
                        Argu2}, this.getStatusOperationCompleted, userState);
        }
        
        private void OngetStatusOperationCompleted(object arg) {
            if ((this.getStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStatusCompleted(this, new getStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPayStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendARReturn GetPayStatus(string CorpID, string PreInvoiceNo) {
            object[] results = this.Invoke("GetPayStatus", new object[] {
                        CorpID,
                        PreInvoiceNo});
            return ((SendARReturn)(results[0]));
        }
        
        /// <remarks/>
        public void GetPayStatusAsync(string CorpID, string PreInvoiceNo) {
            this.GetPayStatusAsync(CorpID, PreInvoiceNo, null);
        }
        
        /// <remarks/>
        public void GetPayStatusAsync(string CorpID, string PreInvoiceNo, object userState) {
            if ((this.GetPayStatusOperationCompleted == null)) {
                this.GetPayStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPayStatusOperationCompleted);
            }
            this.InvokeAsync("GetPayStatus", new object[] {
                        CorpID,
                        PreInvoiceNo}, this.GetPayStatusOperationCompleted, userState);
        }
        
        private void OnGetPayStatusOperationCompleted(object arg) {
            if ((this.GetPayStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPayStatusCompleted(this, new GetPayStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/delALLTiptopPreAccountNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string delALLTiptopPreAccountNo(string Argu1, string Argu2) {
            object[] results = this.Invoke("delALLTiptopPreAccountNo", new object[] {
                        Argu1,
                        Argu2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void delALLTiptopPreAccountNoAsync(string Argu1, string Argu2) {
            this.delALLTiptopPreAccountNoAsync(Argu1, Argu2, null);
        }
        
        /// <remarks/>
        public void delALLTiptopPreAccountNoAsync(string Argu1, string Argu2, object userState) {
            if ((this.delALLTiptopPreAccountNoOperationCompleted == null)) {
                this.delALLTiptopPreAccountNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OndelALLTiptopPreAccountNoOperationCompleted);
            }
            this.InvokeAsync("delALLTiptopPreAccountNo", new object[] {
                        Argu1,
                        Argu2}, this.delALLTiptopPreAccountNoOperationCompleted, userState);
        }
        
        private void OndelALLTiptopPreAccountNoOperationCompleted(object arg) {
            if ((this.delALLTiptopPreAccountNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delALLTiptopPreAccountNoCompleted(this, new delALLTiptopPreAccountNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendTiptop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendTiptop(string Payee) {
            object[] results = this.Invoke("SendTiptop", new object[] {
                        Payee});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendTiptopAsync(string Payee) {
            this.SendTiptopAsync(Payee, null);
        }
        
        /// <remarks/>
        public void SendTiptopAsync(string Payee, object userState) {
            if ((this.SendTiptopOperationCompleted == null)) {
                this.SendTiptopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTiptopOperationCompleted);
            }
            this.InvokeAsync("SendTiptop", new object[] {
                        Payee}, this.SendTiptopOperationCompleted, userState);
        }
        
        private void OnSendTiptopOperationCompleted(object arg) {
            if ((this.SendTiptopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTiptopCompleted(this, new SendTiptopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTiptopDBInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTiptopDBInfo(string key) {
            object[] results = this.Invoke("GetTiptopDBInfo", new object[] {
                        key});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTiptopDBInfoAsync(string key) {
            this.GetTiptopDBInfoAsync(key, null);
        }
        
        /// <remarks/>
        public void GetTiptopDBInfoAsync(string key, object userState) {
            if ((this.GetTiptopDBInfoOperationCompleted == null)) {
                this.GetTiptopDBInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTiptopDBInfoOperationCompleted);
            }
            this.InvokeAsync("GetTiptopDBInfo", new object[] {
                        key}, this.GetTiptopDBInfoOperationCompleted, userState);
        }
        
        private void OnGetTiptopDBInfoOperationCompleted(object arg) {
            if ((this.GetTiptopDBInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTiptopDBInfoCompleted(this, new GetTiptopDBInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SendARReturn {
        
        private bool isSuccessField;
        
        private string accountNoField;
        
        private string accountYearField;
        
        private string msgField;
        
        /// <remarks/>
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
            }
        }
        
        /// <remarks/>
        public string AccountYear {
            get {
                return this.accountYearField;
            }
            set {
                this.accountYearField = value;
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void TestConnCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void setTiptopPreAccountListCompletedEventHandler(object sender, setTiptopPreAccountListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setTiptopPreAccountListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setTiptopPreAccountListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void setTiptopPreAccountListTest2CompletedEventHandler(object sender, setTiptopPreAccountListTest2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setTiptopPreAccountListTest2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setTiptopPreAccountListTest2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void getPayNoCompletedEventHandler(object sender, getPayNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPayNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPayNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void getTipTopAccountNoCompletedEventHandler(object sender, getTipTopAccountNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTipTopAccountNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTipTopAccountNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void delTiptopPreAccountNoCompletedEventHandler(object sender, delTiptopPreAccountNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delTiptopPreAccountNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delTiptopPreAccountNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void getNoCompletedEventHandler(object sender, getNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void getStatusCompletedEventHandler(object sender, getStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetPayStatusCompletedEventHandler(object sender, GetPayStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPayStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPayStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendARReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendARReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void delALLTiptopPreAccountNoCompletedEventHandler(object sender, delALLTiptopPreAccountNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delALLTiptopPreAccountNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delALLTiptopPreAccountNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void SendTiptopCompletedEventHandler(object sender, SendTiptopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTiptopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTiptopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetTiptopDBInfoCompletedEventHandler(object sender, GetTiptopDBInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTiptopDBInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTiptopDBInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591